apiVersion: v1
kind: Service
metadata:
  name: rtc-redis
  labels:
    app: rtc-redis
    env: minikube
spec:
  type: LoadBalancer
  selector:
    app: pepsredis
    env: minikube
  ports:
    - port: 6379
      name: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rtc-redis
  labels:
    app: rtc-redis
    env: minikube
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pepsredis
        env: minikube
    spec:
      containers:
        - name: rtc-redis
          image: redis
          ports:
            - containerPort: 6379
